services:
  - type: web
    name: nivora-erp
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    preDeployCommand: python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: nivora-erp.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: nivora-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: nivora-redis
          property: connectionString

  - type: redis
    name: nivora-redis
    plan: free

databases:
  - name: nivora-db
    plan: free
    postgresqlVersion: 15
