# Generated by Django 4.2.29 on 2026-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_stockreservation_stockreservationline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for line items (edit mode only)'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for line items (edit mode only)'),
        ),
    ]
